name: Caprice Match Racing Team
favicon: null
layout_spectrum: 0.2512
typography_spectrum: 0.75026
title: Caprice Match Racing Team
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8bafde'
    - '#000000'
    - '#00512a'
    - '#ff4500'
    - '#00bd78'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
