name: Caprice Match Racing Team
favicon: null
layout_spectrum: 0.22714590653777122
typography_spectrum: 0.46403388818725944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.33904451248236
  lightness: 0.9293297894764692
  saturation: 0.7561059056315571
  rhythmicContrast: 0.8020602883771062
purpose: []
